apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-operator
  labels:
    dynatrace: operator
    operator: activegate
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
