apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-dynakube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-dynakube
subjects:
  - kind: ServiceAccount
    name: dynatrace-dynakube
    namespace: dynatrace
