apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-operator
  labels:
    dynatrace: operator
    operator: activegate
subjects:
  - kind: ServiceAccount
    name: dynatrace-activegate-operator
    namespace: dynatrace
roleRef:
  kind: ClusterRole
  name: dynatrace-operator
  apiGroup: rbac.authorization.k8s.io
