apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole-dynakube.yaml
  - clusterrolebinding-dynakube.yaml
  - deployment-operator.yaml
  - role-operator.yaml
  - rolebinding-operator.yaml
  - serviceaccount-dynakube.yaml
  - serviceaccount-operator.yaml
  - podsecuritypolicy-dynakube.yaml
  - podsecuritypolicy-operator.yaml
bases:
  - ../crds
