apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dynatrace-activegate-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: activegate
rules:
- apiGroups:
    - dynatrace.com
  resources:
    - activegates
  verbs:
    - get
    - list
    - watch
    - update
    - create

- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
    - delete
    - create

- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
