apiVersion: v1
kind: Service
metadata:
  name: dynatrace-webhook
  namespace: dynatrace
  labels:
    dynatrace.com/operator: dynakube
    internal.oneagent.dynatrace.com/component: webhook
spec:
  selector:
    internal.oneagent.dynatrace.com/app: webhook
    internal.oneagent.dynatrace.com/component: webhook
  ports:
  - port: 443
    protocol: TCP
    targetPort: server-port
