name: Build Docker Image
description: Builds the operator docker image
inputs:
  platform:
    required: true
  go-version:
    required: true
  go-linker-args:
    required: true
  cgo-cflags:
    required: true
  labels:
    required: true
  image-tag:
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ./third_party_licenses
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - name: Prepare
        run: |
          hack/build/ci/download-go-build-deps.sh
      - name: Build target
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            GO_LINKER_ARGS=${{ inputs.go-linker-args }}
            CGO_CFLAGS=${{ inputs.cgo-cflags }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ inputs.platform }}
          push: false
          tags: operator-${{ inputs.platform }}:${{ inputs.image-tag }}
          labels: ${{ inputs.labels }}
          outputs: type=docker,dest=/tmp/operator-${{ inputs.platform }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: operator-${{ inputs.platform }}
          path: /tmp/operator-${{ inputs.platform }}.tar
          retention-days: 1

