name: Create Manifests
description: Creates the manifests for the images
inputs:
  version:
    required: true
  registry:
    required: true
  repository:
    required: true
  combined:
    required: true
secrets:
  docker_repo_username:
    required: true
  docker_repo_password:
    required: true
runs:
  using: "composite"
  env:
    IMAGE_QUAY: ${{ inputs.registry }}/${{ inputs.repository }}
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Create manifest
      run: |
        hack/build/ci/create-manifest.sh "${IMAGE_QUAY}" "${{ inputs.version }}" ${{ inputs.combined }}
