name: Upload Docker Image
description: Uploads the operator docker image to a registry
inputs:
  platform:
    required: true
  labels:
    required: true
  version:
    required: true
  registry:
    required: true
  repository:
    required: true
  docker-repo-username:
    required: true
  docker-repo-password:
    required: true
runs:
  using: "composite"
  env:
    TARGET_IMAGE_TAG: ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.version }}-${{ inputs.platform }}
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.docker-repo-username }}
        password: ${{ inputs.docker-repo-password }}
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: operator-${{ inputs.platform }}
        path: /tmp
    - name: Upload image to Registry
      run: |
        hack/build/ci/upload-docker-image.sh "${{ inputs.platform }}" "${TARGET_IMAGE_TAG}"
