apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dynatrace-dynakube-oneagent
rules:
- apiGroups:
  - policy
  resourceNames:
  - dynatrace-dynakube-oneagent
  resources:
  - podsecuritypolicies
  verbs:
  - use
