apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../common
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: dynatrace-monitoring-operator-cluster
    path: clusterrole-monitoring-patch.yaml
