name: upload-dockerimage

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      labels:
        required: true
        type: string
      version:
        required: true
        type: string
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      docker_repo_username:
        required: true
      docker_repo_password:
        required: true
      snyk_token:
        required: true

permissions:
  contents: read

jobs:
  upload_job:
    name: Upload docker image to Registry
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE_TAG: ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.version }}-${{ inputs.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.docker_repo_username }}
          password: ${{ secrets.docker_repo_password }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: operator-${{ inputs.platform }}
          path: /tmp
      - name: Upload image to Registry
        run: |
          hack/build/ci/upload-docker-image.sh "${{ inputs.platform }}" "${TARGET_IMAGE_TAG}"
      - name: Snyk Container Image Check
        uses: snyk/actions/docker@7a25034bb99f934b1e45b08d2025b07dde28aa48
        # if: github.ref_protected == 'true'
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          image: ${{ env.TARGET_IMAGE_TAG }}
          args: --severity-threshold=high --file=Dockerfile --sarif-file-output=image.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@96bc9c36c68e097cd033777efed25c248ffcf09a
        # if: github.ref_protected == 'true'
        with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: image.sarif
